services:
  - type: web
    name: dijkstra-frontend
    env: static
    buildCommand: npm run install-deps && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: dijkstra-backend
    env: node
    buildCommand: cd backend/baceknd && npm install
    startCommand: cd backend/baceknd && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
